# Generated by Django 4.2.4 on 2023-08-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='О специалисте'),
        ),
    ]
