# Generated by Django 4.2.4 on 2023-08-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_master_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальность'),
        ),
    ]
